apiVersion: v1
kind: Service
metadata:
  name: dotnet-sample
  labels:
    app: dotnet-sample
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dotnet-sample

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-sample
  labels:
    app: dotnet-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-sample
  template:
    metadata:
      labels:
        app: dotnet-sample
    spec:
      containers:
      - name: dotnet-sample
        image: ghcr.io/dotariel/dotnet
        ports:
        - containerPort: 5000